---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: capz-demo-control-plane
  namespace: default
spec:
  version: $KUBERNETES_VERSION
  replicas: 1
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AzureMachineTemplate
    name: capz-demo-control-plane
  kubeadmConfigSpec:
    clusterConfiguration:
      kubernetesVersion: $KUBERNETES_VERSION
      apiServer:
        extraArgs:
          cloud-config: /etc/kubernetes/azure.json
          cloud-provider: azure
        extraVolumes:
        - hostPath: /etc/kubernetes/azure.json
          mountPath: /etc/kubernetes/azure.json
          name: cloud-config
          readOnly: true
        timeoutForControlPlane: 20m
      controllerManager:
        extraArgs:
          allocate-node-cidrs: "true"
          cloud-config: /etc/kubernetes/azure.json
          cloud-provider: azure
        extraVolumes:
        - hostPath: /etc/kubernetes/azure.json
          mountPath: /etc/kubernetes/azure.json
          name: cloud-config
          readOnly: true
    files:
    - content: |
        {
          "cloud": "AzurePublicCloud",
          "tenantId": "$AZURE_TENANT_ID",
          "subscriptionId": "$AZURE_SUBSCRIPTION_ID",
          "aadClientId": "$AZURE_CLIENT_ID",
          "aadClientSecret": "$AZURE_CLIENT_SECRET",
          "resourceGroup": "capz-demo",
          "securityGroupName": "capz-demo-node-nsg",
          "location": "westeurope",
          "vmType": "standard",
          "vnetName": "capz-demo-vnet",
          "vnetResourceGroup": "capz-demo",
          "subnetName": "capz-demo-node-subnet",
          "routeTableName": "capz-demo-node-routetable",
          "userAssignedID": "capz-demo",
          "loadBalancerSku": "standard",
          "maximumLoadBalancerRuleCount": 250,
          "useManagedIdentityExtension": false,
          "useInstanceMetadata": true
        }
      owner: root:root
      path: /etc/kubernetes/azure.json
      permissions: "0644"
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-config: /etc/kubernetes/azure.json
          cloud-provider: azure
        name: '{{ ds.meta_data["local_hostname"] }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-config: /etc/kubernetes/azure.json
          cloud-provider: azure
        name: '{{ ds.meta_data["local_hostname"] }}'
    preKubeadmCommands:
    - curl -Lo /tmp/kubeadm-bootstrap.sh https://raw.githubusercontent.com/ionutbalutoiu/cloudbase-init-capz-demo/update-guide/scripts/kubeadm-bootstrap.sh
    - bash /tmp/kubeadm-bootstrap.sh
    useExperimentalRetryJoin: true
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureMachineTemplate
metadata:
  name: capz-demo-control-plane
  namespace: default
spec:
  template:
    spec:
      location: westeurope
      osDisk:
        diskSizeGB: 128
        managedDisk:
          storageAccountType: Premium_LRS
        osType: Linux
      sshPublicKey: $AZURE_SSH_PUBLIC_KEY_B64
      vmSize: Standard_D2s_v3
