---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-proxy-windows
  namespace: kube-system
  labels:
    app: kube-proxy
data:
  init.ps1: |
    $ErrorActionPreference = "Stop"

    mkdir -force /host/k/kube-proxy
    mkdir -force /host/var/lib/kube-proxy/var/run/secrets/kubernetes.io/serviceaccount

    cp -force /var/lib/kube-proxy/* /host/var/lib/kube-proxy
    cp -force /var/run/secrets/kubernetes.io/serviceaccount/* /host/var/lib/kube-proxy/var/run/secrets/kubernetes.io/serviceaccount #FIXME?
    cp -force /k/kube-proxy/kube-proxy.exe /host/k/kube-proxy/kube-proxy.exe

    $networkName = (Get-Content /host/etc/cni/net.d/10-flannel.conf | ConvertFrom-Json).name
    $flannelSubnet = ((Get-Content /host/run/flannel/subnet.env) | Where-Object { $_.StartsWith("FLANNEL_SUBNET=") }).Trim("FLANNEL_SUBNET=")
    $sourceVip = $flannelSubnet.Split(".")[0..2] + 0 -join "."

    yq w -i /host/var/lib/kube-proxy/config.conf winkernel.networkName $networkName
    yq w -i /host/var/lib/kube-proxy/config.conf winkernel.sourceVip $sourceVip
    yq w -i /host/var/lib/kube-proxy/config.conf featureGates.WinOverlay true
    yq w -i /host/var/lib/kube-proxy/config.conf mode "kernelspace"

  run.ps1: |
    wins cli process run --path /k/kube-proxy/kube-proxy.exe --args "--v=4 --config=/var/lib/kube-proxy/config.conf --hostname-override=$env:NODE_NAME"

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-proxy-windows
  namespace: kube-system
  labels:
    k8s-app: kube-proxy
spec:
  selector:
    matchLabels:
      k8s-app: kube-proxy-windows
  template:
    metadata:
      labels:
        k8s-app: kube-proxy-windows
    spec:
      serviceAccountName: kube-proxy
      initContainers:
      - name: init-kube-proxy
        image: e2eteam/kube-proxy-windows:v1.18.8-windowsservercore-ltsc2019
        imagePullPolicy: Always
        command:
        - powershell
        args:
        - -file
        - /var/lib/kube-proxy-windows/init.ps1
        volumeMounts:
        - name: host
          mountPath: /host
        - name: wins
          mountPath: \\.\pipe\rancher_wins
        - name: kube-proxy
          mountPath: /var/lib/kube-proxy
        - name: kube-proxy-windows
          mountPath: /var/lib/kube-proxy-windows
      containers:
      - name: kube-proxy
        image: e2eteam/kube-proxy-windows:v1.18.8-windowsservercore-ltsc2019
        imagePullPolicy: Always
        command:
        - powershell
        args:
        - -file
        - /var/lib/kube-proxy-windows/run.ps1
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        volumeMounts:
        - name: host
          mountPath: /host
        - name: wins
          mountPath: \\.\pipe\rancher_wins
        - name: kube-proxy-windows
          mountPath: /var/lib/kube-proxy-windows
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          name: kube-proxy-windows
        name: kube-proxy-windows
      - configMap:
          name: kube-proxy
        name: kube-proxy
      - hostPath:
          path: /
        name: host
      - name: wins
        hostPath:
          path: \\.\pipe\rancher_wins
          type: null
  updateStrategy:
    type: RollingUpdate